[src]:branches/VS/obsproc_global/jobs
M    JGFS_PREP
M    JCDAS_PREP1
M    JCDAS_PREP2
M    JGDAS_PREP

Modified the noted prep jobs to reset global environmental variable $TMPDIR to $DATAROOT.  This adjustment is more thoroughly explained in change set #36441 committed by Dennis Keyser.

diff --git a/jobs/JCDAS_PREP2 b/jobs/JCDAS_PREP2
--- a/jobs/JCDAS_PREP2
+++ b/jobs/JCDAS_PREP2
@@ -1,14 +1,44 @@
-#!/bin/sh
+set -xa
+date -u
 
-set -xa     
+if [ -n "$obsproc_global_ver" ]; then
+   set +x
+   echo
+   echo "Current OBSPROC_GLOBAL version is $obsproc_global_ver"
+   echo
+   set -x
+fi
+if [ -n "$obsproc_prep_ver" ]; then
+   set +x
+   echo
+   echo "OBSPROC_PREP version used by this job is $obsproc_prep_ver"
+   echo
+   set -x
+fi
 
-######################################################
-# The following variable could be defined in the LSF
-# submission script (the ECFLOW script), if not it
-# will take the default value which is set for the
-# NCO running environment
-######################################################
-export RUN_ENVIR=${RUN_ENVIR:-prod}
+###################################################################
+# Set DEBUG LEVEL - modifies info in execution trace prompt string
+###################################################################
+export DEBUG_LEVEL=${DEBUG_LEVEL=1}
+case $DEBUG_LEVEL in
+  1) export PS4='+ ${SECONDS}s + ' ;;       # add seconds (this is typical case)
+  0) export PS4='+ ';;                      # don't include seconds (useful if
+                                            #  want to diff output from 2 runs)
+  2) export PS4='+ ${SECONDS}s:L$LINENO + ';;         # add script line #
+  3) export PS4='+ ${SECONDS}s:${0##*/}:L$LINENO + ';;# add script name & line #
+  *) echo "Unrecognized DEBUG_LEVEL.  Stay with current PS4 setting";;
+esac
+
+########################################
+# Check that required variables are set
+########################################
+set +x
+echo
+echo cyc is ${cyc:?"###FATAL ERROR \"cyc\" is not set"}
+echo envir is ${envir:?"###FATAL ERROR \"envir\" is not set"}
+echo job is ${job:?"###FATAL ERROR \"job\" is not set"}
+echo
+set -x
 
 ###########################
 # Specify NET and RUN Name
@@ -16,92 +46,114 @@ export RUN_ENVIR=${RUN_ENVIR:-prod}
 export NET=${NET:-cdas}
 export RUN=${RUN:-cdas}
 
-if [ $envir = "prod" ]
-then
-   export SENDDBN=${SENDDBN:-YES}
-   export jlogfile=${jlogfile:-/com/logs/jlogfiles/jlogfile.${job}.$$}
+##############################
+# Specify cycle and time-mark
+##############################
+export cycle=t${cyc}z
+export tmmark=tm00
+
+###############################
+# Create new working directory
+###############################
+host=$(hostname -s)
+if [[ ${USER} == nwprod ]]; then
+  DATAROOT=/tmpnwprd
 else
-   export SENDDBN=${SENDDBN:-NO}
-   export jlogfile=${jlogfile:-/com/logs/${envir}/jlogfile}
-   export COM=${COM:-/com/${NET}/${envir}}
-   export COM_IN=${COM_IN:-/com/${NET}/${envir}}
-   export COM1=${COM1:-/com/${NET}/${envir}/${RUN}.}
-   export COM_OUT=${COM_OUT:-/com/${NET}/${envir}}
-   export COMIN=${COMIN:-/com/${NET}/${envir}/${RUN}.${PDY}}
-   export COMOUT=${COMOUT:-/com/${NET}/${envir}/${RUN}.${PDY}}
-   export PARMPREP=/nwtest/parm
-   export envir_getges=prod
-   export USHGETGES=/nwprod/util/ush
+  DATAROOT=${DATAROOT:-/stmp/${USER}}
+  TMPDIR=$DATAROOT  # On WCOSS TMPDIR is reset to a temporary LSF
+                    #  directory when jobs are submitted, set it
+                    #  to $DATAROOT so its under the user's control
 fi
-
-#################################
-# SET SHELL PROCESSING VARIABLES
-#################################
-export PS4='$SECONDS + '
-date
-
-#################################################
-# SETUP CDAS PREPBUFR PREP2 PROCESSING VARIABLES
-#################################################
-
-#########################################################
-# obtain unique process id (pid) and make temp directory
-#########################################################
-export pid=$$
-export DATA_IN=${DATA_IN:-/tmpnwprd}
-export DATA=${DATA:-$DATA_IN/${job}.${pid}}
-
-CLEAN=${CLEAN:-YES}
-if [ $CLEAN = YES ]; then
-   rm -r -f $DATA
-fi
+export DATA=${DATA:-$DATAROOT/${job}.${host}.$$}
+rm -rf $DATA
 mkdir -p $DATA
 cd $DATA
 
-###################
-# File To Log Msgs
-###################
-export jlogfile=${jlogfile:-/com/logs/jlogfiles/jlogfile.${job}.${pid}}
-
-export cycle=t${cyc}z
-export tmmark=tm00
+######################################
+# Set job log file for postmsg output
+######################################
+if [[ ${USER} == nwprod ]]; then
+  if [[ ${envir} == prod ]]; then
+    jlogfile=/com/logs/jlogfiles/jlogfile.${job}.$$
+  else
+    jlogfile=/com/logs/${envir}/jlogfile
+  fi
+else
+  jlogfile=${jlogfile:-${DATA}/jlogfile}
+fi
 
 ######################################
 # Determine Job Output Name on System
 ######################################
+export pid=$$
 export outid="LL$job"
 [ $envir != prod ]  && export outid="LL${job}_${envir}"
 export jobid="${outid}.o${pid}"
 export pgmout="OUTPUT.${pid}"
 
-##################################################################
-# SENDCOM=YES   - Copy output files to /com directory
-# SENDECF=YES   - Flag Events on ECFLOW
-# SENDDBN=YES   - Alert output file to TOC, set to NO for testing
-# GET_IOPROFILE - Run I/O statistics
-##################################################################
-export SENDCOM=${SENDCOM:-YES}
-export SENDECF=${SENDECF:-YES}
-export SENDDBN=${SENDDBN:-YES}       # need to set to NO for testing only
-export GET_IOPROFILE=${GET_IOPROFILE:-NO}
-
-export HOMEcdas=${HOMEcdas:-/nw${envir}}
-export FIXcdas=${FIXcdas:-$HOMEcdas/fix}
-export SCRIPTScdas=${SCRIPTScdas:-$HOMEcdas/scripts}
+################################################
+# SENDCOM      - Copy files to /com directory
+# SENDECF      - Flag Events on ECFLOW
+# SENDDBN      - Alert output file to TOC
+# SENDDBN_GB2  - Alert output GRIB2 file to TOC
+################################################
+if [[ ${USER} == nwprod ]]; then
+  export SENDCOM=YES
+  export SENDECF=YES
+  if [[ ${envir} == prod ]]; then
+    export SENDDBN=YES
+    export SENDDBN_GB2=YES
+  else
+    export SENDDBN=NO
+    export SENDDBN_GB2=NO
+  fi
+else  # developer
+  export SENDCOM=${SENDCOM:-YES}
+  export SENDECF=NO
+  export SENDDBN=NO
+  export SENDDBN_GB2=NO
+fi
 
 ##########################
 # Specify Execution Areas
 ##########################
-export HOMEPREP=${HOMEPREP:-/nwprod}
-export EXECPREP=${EXECPREP:-${HOMEPREP}/exec}
-export FIXPREP=${FIXPREP:-${HOMEPREP}/fix}
-export PARMPREP=${PARMPREP:-${HOMEPREP}/parm}
-export DICTPREP=${DICTPREP:-${HOMEPREP}/dictionaries}
 
-export HOMESYND=${HOMESYND:-/nwprod}
+# -------------------------------
+# Paths for obsproc_network items
+# -------------------------------
+export HOMEobsproc_network=${HOMEobsproc_network:\
+-/nw${envir}/obsproc_global.${obsproc_global_ver:?\
+"###FATAL ERROR \"obsproc_global_ver\" is not set"}}
+
+export SCRIPTSobsproc_global=${SCRIPTSobsproc_global:\
+-$HOMEobsproc_network/scripts}
+
+export FIXobsproc_global=${FIXobsproc_global:-$HOMEobsproc_network/fix}
+
+# ----------------------------
+# Paths for obsproc_prep items
+# ----------------------------
+export HOMEobsproc_prep=${HOMEobsproc_prep:\
+-/nw${envir}/obsproc_prep.${obsproc_prep_ver:?\
+"###FATAL ERROR \"obsproc_prep_ver\" is not set"}}
+
+# directory path to data prep script executed in model script
+# -----------------------------------------------------------
+export ushscript_prep=${ushscript_prep:-$HOMEobsproc_prep/ush}
+
+# ---------------------------------------------------------
+# Paths for combined obsproc_network and obsproc_prep items
+# ---------------------------------------------------------
+
+export EXECPREP=${EXECPREP:-${HOMEobsproc_prep}/exec}
+export FIXPREP=${FIXPREP:-${HOMEobsproc_prep}/fix}
+export PARMPREP=${PARMPREP:-${HOMEobsproc_network}/parm}
+export DICTPREP=${DICTPREP:-/nwprod/dictionaries}
+
+export HOMESYND=${HOMESYND:-$HOMEobsproc_prep}
 export EXECSYND=${EXECSYND:-${HOMESYND}/exec}
 export FIXSYND=${FIXSYND:-${HOMESYND}/fix}
-export PARMSYND=${PARMSYND:-${HOMESYND}/parm}
+export PARMSYND=${PARMSYND:-${HOMEobsproc_network}/parm}
 
 export HOMEUTIL=${HOMEUTIL:-/nwprod/util}
 export EXECUTIL=${EXECUTIL:-${HOMEUTIL}/exec}
@@ -109,18 +161,18 @@ export EXECUTIL=${EXECUTIL:-${HOMEUTIL}/exec}
 #######################
 # Set up the UTILITIES
 #######################
-export ushscript=${ushscript:-/nwprod/ush}
 export utilscript=${utilscript:-/nwprod/util/ush}
 export utilparm=${utilparm:-/nwprod/util/parm}
 export utilexec=${utilexec:-/nwprod/util/exec}
-export utilities=${utilities:-/nwprod/util/ush}
 
 ################################################################
 # Run setup to initialize working directory and utility scripts
 ################################################################
-sh $utilscript/setup.sh
-cp /usr/bin/time $DATA/time
-chmod 755 $DATA/time
+if [[ ${USER} == nwprod ]]; then
+  sh $utilscript/setup.sh
+else
+  sh ${SETUP:-/nwprod/util/ush}/setup.sh
+fi
 
 ##########################################
 # Run setpdy and initialize PDY variables
@@ -186,17 +238,29 @@ sh $utilscript/setpdy.sh
 #########################
 # Define COM directories
 #########################
-export COM_IN_ROOT=${COM_IN_ROOT:-/com}
-export COM_IN=${COM_IN:-${COM_IN_ROOT}/${NET}/${envir}}
-export COM1=${COM1:-${COM_IN}/${RUN}.}
-export COM_OUT_ROOT=${COM_OUT_ROOT:-/com}
-export COM_OUT=${COM_OUT:-${COM_OUT_ROOT}/${NET}/${envir}}
+if [ "$LSB_UNIXGROUP_INT" = 'prod' ]; then
+  export COMIN=/com/${NET}/${envir}/${RUN}.${PDY}
+  export COMOUT=/com/${NET}/${envir}/${RUN}.${PDY}
+  mkdir -m 775 -p $COMOUT
+else
+  export COMIN_ROOT=${COMIN_ROOT:-/com}
+  export COMIN=${COMIN:-${COMIN_ROOT}/${NET}/${envir}/${RUN}.${PDY}}
 
-export COM=${COM:-${COM_IN}}
-export COMIN=${COMIN:-${COM_IN}/${RUN}.${PDY}}
-export COMOUT=${COMOUT:-${COM_OUT}/${RUN}.${PDY}}
+# COMOUT_ROOT for developers defaults to unique $DATA/com directory as root to
+#  prevent job from writing into a non-unique directory (e.g., /ptmp/$USER/com)
+#  that might already have a dump status file in it from a previous checkout
+#  run (this could mess up some logic downstream) -- since $DATA is not
+#  necessarily known at time COMOUT_ROOT would have to be exported in parent
+#  script we go with $DATA/com as default here
+# -----------------------------------------------------------------------------
+  export COMOUT_ROOT=${COMOUT_ROOT:-${DATA}/com}
+  export COMOUT=${COMOUT:-${COMOUT_ROOT}/${NET}/${envir}/${RUN}.${PDY}}
+  mkdir -m 755 -p $COMOUT
+fi
 
-mkdir -m 775 -p $COMOUT
+#################################################
+# SETUP CDAS PREPBUFR PREP2 PROCESSING VARIABLES
+#################################################
 
 #########################################################
 # Specify variables specific to this execution of script
@@ -265,14 +329,8 @@ env
 #####################
 # Execute the script
 #####################
-if [ $GET_IOPROFILE = YES ]; then
-   /usrx/local/mio/tools/bin/miostats -X0 \
-   $SCRIPTScdas/exglobal_makeprepbufr.sh.ecf
-   err_cdas_prep2=$?
-else
-   $SCRIPTScdas/exglobal_makeprepbufr.sh.ecf
-   err_cdas_prep2=$?
-fi
+$SCRIPTSobsproc_global/exglobal_makeprepbufr.sh.ecf
+eval err_${RUN}_prep1=$?
 
 COPY_TO_ARKV=${COPY_TO_ARKV:-YES}
 if [ $COPY_TO_ARKV = YES ]; then
@@ -293,22 +351,22 @@ if [ $COPY_TO_ARKV = YES ]; then
     /com/arkv/${envir}/cdas.${ARKPDY}/tosscat${PDY}${cyc}
    #cp $LOADL_STEP_OUT /com/arkv/${envir}/cdas.${ARKPDY}/prep2${PDY}${cyc}.out
    cp $LSB_OUTPUTFILE /com/arkv/${envir}/cdas.${ARKPDY}/prep2${PDY}${cyc}.out
-
 fi
 
-#################################################
-# Save the profiling data captured from miostats
-#################################################
-if [ $GET_IOPROFILE = YES ]; then
-    . /com/miostats/.set_IOprofile
-fi
+echo "`hostname`  --  `date -u`" > $COMOUT/where_${cycle}_${RUN}_prep_ran
 
-CLEAN=${CLEAN:-YES}
-if [ $CLEAN = YES ]; then
-   cd $DATA_IN
+> $COMOUT/obsproc_version_for_${cycle}_${RUN}_prep_run
+[ -n "$obsproc_global_ver" ]  &&  \
+ echo "Current OBSPROC_GLOBAL version is $obsproc_global_ver" >> \
+ $COMOUT/obsproc_version_for_${cycle}_${RUN}_prep_run
+[ -n "$obsproc_prep_ver" ]  &&  \
+ echo "OBSPROC_PREP version used by this job is $obsproc_prep_ver" >> \
+ $COMOUT/obsproc_version_for_${cycle}_${RUN}_prep_run
+
+if [ "${CLEANUP:-YES}" = YES ]; then
+   cd $DATAROOT
    rm -rf $DATA
 fi
+date -u
 
-date
-#ecflow_client --complete
-
+exit
